name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Format Check
      run: |
        unformatted=$(gofmt -l ./nft)
        test -z "$unformatted" || (echo "Unformatted: $unformatted" && false)

    - name: Import Format Check
      run: |
        go get golang.org/x/tools/cmd/goimports
        unformatted=$(goimports -l --local "github.com/eddev/go-nft" ./nft)
        test -z "$unformatted" || (echo "Unformatted imports: $unformatted" && false)

    - name: Build
      run: go build -v ./...

    - name: Run Unit Tests
      run: go test -v ./nft

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Docker Service
        run: sudo service docker start

      - name: Run Integration Tests
        run: ./automation/run-tests.sh
