name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Format Check
      run: ./automation/run-tests.sh --fmt

    - name: Build
      run: ./automation/run-tests.sh --build

    - name: Run Unit Tests
      run: ./automation/run-tests.sh --unit-test

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Docker Service
        run: sudo service docker start

      - name: Run Integration Tests
        run: ./automation/run-tests.sh --integration-test
